# Generated by Django 3.1.7 on 2021-04-12 20:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, default='')),
                ('important', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('date_to_complete', models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 13, 23, 31, 36, 309949))),
                ('status', models.CharField(choices=[('A', 'Active'), ('P', 'Postponed'), ('D', 'Done')], default='A', max_length=1)),
                ('author', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
