# Generated by Django 3.1.7 on 2021-03-30 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_edited', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('text', models.TextField(blank=True, default='')),
                ('important', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('A', 'Active'), ('P', 'Postponed'), ('D', 'Done')], default='A', max_length=1)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
